pix/urls.py
from django.urls import path
from . import views
from .views import deposit
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pix'
urlpatterns = [
    path("", views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path("collections/", views.collections , name='collections'),
    path('full_collection/<str:image_name>/', views.full_collection, name='full_collection'),
    path("create/", views.create , name='create'),
    path("dashboard/", views.dashboard , name='dashboard'),
    path("explore/", views.explore , name='explore'),
    path("notifications/", views.notifications , name='notifications'),
    path("Privacy/", views.privacy , name='Privacy'),
    path('settings/', views.settings_view, name='settings'),
    path('logout/', views.custom_logout, name='logout'),
    path('notifications/', views.notifications_view, name='notifications'),
    path("Terms/", views.Terms , name='Terms'),
    path('view_collections/<str:image_name>/', views.view_collections, name='view_collections'),
    path("collection_purchase/", views.collection_purchase , name="collection_purchase"),
    path('deposit/', deposit, name='deposit'),
    path('withdraw/', views.withdraw, name='withdraw'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pixels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


def home_redirect(self):
    return redirect("/pix")


urlpatterns = [
    path("", home_redirect),
    path("pix/", include("pix.urls")),
    path("admin/", admin.site.urls),
    path("pix/wform/", include("wform.urls")),
    #    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pix/models.py
from django.db import models
from django.contrib.auth.models import User

class Balance(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, null=True, blank=True)

    def __str__(self):
        return f"{self.balance}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Image(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.category} - {self.name}"
    
class ImageFile(models.Model):
    image = models.ImageField(upload_to='images/')
    image_info = models.ForeignKey(Image, on_delete=models.CASCADE)

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    title = models.CharField(max_length=255)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} - {self.message}"
    


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures/', default='default.jpg')

    def __str__(self):
        return self.user.username


class CollectionClickLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user.username} clicked at {self.timestamp}"
    


class Deposit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.amount}'
    

class Withdrawal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    withdrawal_date = models.DateTimeField(auto_now_add=True)
    is_withdrawal = models.CharField(choices=(("true", "true"), ("false","false")) ,default="false", max_length=20)

    def __str__(self):
        return f"{self.user.username} - {self.amount}"


class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('credit', 'Credit'),
        ('debit', 'Debit'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    transaction_type = models.CharField(max_length=6, choices=TRANSACTION_TYPES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username} - {self.transaction_type} - {self.amount}"

pix/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Image, Category, Profile, ImageFile, Deposit
from multiupload.fields import MultiFileField



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'username': 'Username',
            'email': 'Email',
            'password1': 'Password',
            'password2': 'Confirm Password',
        }
        help_texts = {
            'username': '',
            'password1': '',
            'password2': '',
        }
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Username or Email')

# here
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ImageUploadForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True)
    images = MultiFileField(label='Select files', required=False)
    

    class Meta:
        model = Image
        fields = ['category', 'name', 'price']


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_picture']


class ProfileSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']



class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ['amount']

pix/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm, UserLoginForm, ProfilePictureForm, ProfileSettingsForm
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages
from .models import Balance, Notification, CollectionClickLog, Deposit
from django.contrib.auth.decorators import login_required
from .forms import ImageUploadForm
from .models import Image, Category, Profile, ImageFile, Withdrawal, Transaction
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from .models import User  # Assuming 'User' is in your app's models.py
from .forms import DepositForm
from django.db.models import Q




def index(request):
    template = loader.get_template('pix/index.html')
    context = {}
    rendered_template = template.render(context, request)
    return HttpResponse(rendered_template)

# def collection_purchase(request):
#     template = loader.get_template('pix/collection_purchase.html')
#     context = {}
#     rendered_template = template.render(context, request)
#     return HttpResponse(rendered_template)


@login_required
def collection_purchase(request):
    if request.method == "POST":
        # Log the click
        CollectionClickLog.objects.create(user=request.user)
        # Handle the purchase logic here
        # ...
        return redirect('pix:collection_purchase')
    return render(request, 'pix/collection_purchase.html')



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('pix:dashboard')
    else:
        form = UserRegisterForm()
    return render(request, 'pix/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_superuser:
                    form.add_error(None, "Invalid username or password")
                else:
                    auth_login(request, user)
                    return redirect('pix:dashboard')
            else:
                form.add_error(None, "Invalid username or password")
    else:
        form = UserLoginForm()
    return render(request, 'pix/login.html', {'form': form})

def custom_logout(request):
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'You have been logged out successfully.')
        return redirect('pix:index')
    else:
        return redirect('pix:login')






@login_required
def collections(request):
    images_by_category = {}

    # Filter images by the logged-in user
    images = ImageFile.objects.filter(image_info__user=request.user)

    for image in images:
        category_name = image.image_info.category
        # Check if category_name already exists in images_by_category
        # If it doesn't, add it to the dictionary
        if category_name not in images_by_category:
            images_by_category[category_name] = image

    return render(request, 'pix/collections.html', {'images_by_category': images_by_category})


@login_required
def full_collection(request, image_name):
    images_info = Image.objects.filter(name=image_name)
    images = ImageFile.objects.filter(image_info__in=images_info)
    return render(request, 'pix/full_collection.html', {'image_name': image_name, 'images': images})


@login_required
# def create(request):
#     upload_cost = 180
#     if request.method == 'POST':
#         form = ImageUploadForm(request.POST, request.FILES)
#         if form.is_valid():
#             user_balance = Balance.objects.get_or_create(user=request.user)[0]

#             if user_balance.balance >= upload_cost:
#                 user_balance.balance -= upload_cost
#                 user_balance.save()

#                 image = form.save(commit=False)
#                 image.user = request.user
#                 image.save()

#                 # here
#                 images = request.FILES.getlist('images')
#                 for img in images:
#                     ImageFile.objects.create(image=img, image_info=image)

#                 messages.success(request, 'Image uploaded successfully and amount deducted from your balance.')
#                 return redirect('pix:explore')
#             else:
#                 messages.error(request, 'Insufficient balance to upload the image.')
#         else:
#             messages.error(request, 'Invalid form submission.')
#     else:
#         form = ImageUploadForm()
#     return render(request, 'pix/create.html', {'form': form})


@login_required
def create(request):
    upload_cost_per_file = 96
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            user_balance = Balance.objects.get_or_create(user=request.user)[0]

            # Get the list of uploaded files
            images = request.FILES.getlist('images')
            number_of_files = len(images)
            total_upload_cost = upload_cost_per_file * number_of_files

            if user_balance.balance >= total_upload_cost:
                user_balance.balance -= total_upload_cost
                user_balance.save()

                # Save the main Image object
                image = form.save(commit=False)
                image.user = request.user
                image.save()

                # Handle multiple file uploads for ImageFile
                for img in images:
                    ImageFile.objects.create(image=img, image_info=image)

                messages.success(request, f'Image uploaded successfully and ${total_upload_cost} deducted from your balance.')
                return redirect('pix:explore')
            else:
                messages.error(request, 'Insufficient balance to upload the images.')
        else:
            messages.error(request, 'Invalid form submission.')
    else:
        form = ImageUploadForm()
    return render(request, 'pix/create.html', {'form': form})




def explore(request):
    q = request.GET.get('q', '')  # Get 'q' parameter from request.GET or set it to an empty string if not present
    if q:
        categories = Category.objects.filter(Q(name__icontains=q) | Q(image__name__icontains=q))
    else:
        categories = Category.objects.all()

    images_by_category = {}

    for category in categories:
        images = ImageFile.objects.filter(image_info__category=category, image_info__name__icontains=q)
        filtered_images = []
        seen_names = set()  # Initialize a set to track seen names

        for image in images:
            if image.image_info.name not in seen_names:  # Check if the name is not in the set
                filtered_images.append(image)
                seen_names.add(image.image_info.name)  # Add the name to the set

        if filtered_images:  # Check if there are any filtered images for the category
            images_by_category[category.name] = filtered_images

    return render(request, 'pix/explore.html', {
        'images_by_category': images_by_category,
    })


#Elvis End >>>>>>>>>>>>>>>>>>>>>>>>

@login_required
def view_collections(request, image_name):
    images_info = Image.objects.filter(name=image_name)
    images = ImageFile.objects.filter(image_info__in=images_info)
    return render(request, 'pix/view_collections.html', {'image_name': image_name, 'images': images})



# def deposit(request):
#     if request.method == 'POST':
#         amount = request.POST.get('amount')
#         user_id = request.POST.get('user_id')

#         # Save the deposit
#         deposit = Deposit.objects.create(amount=amount, user_id=user_id)

#         return redirect('admin:pix_deposit_changelist')  # Redirect to admin page after deposit

#     return JsonResponse({'status': 'error'})

@login_required
def dashboard(request):
    deposit_form = DepositForm()
    if request.method == "POST":
        amount = request.POST.get("amount")
        deposit = Deposit.objects.create(amount=amount, user=request.user)
    
    user_balance = Balance.objects.get_or_create(user=request.user)[0]
    user_image_count = Image.objects.filter(user=request.user).count()
    transactions = Transaction.objects.filter(user=request.user)

    context = {
        'user_balance': user_balance,
        'user_image_count': user_image_count,
        'deposit_form': deposit_form,
        'transactions': transactions
    }
    
    return render(request, 'pix/dashboard.html', context)


@login_required
def notifications(request):
    user_notifications = Notification.objects.filter(user=request.user)
    context = {'notifications': user_notifications}
    return render(request, 'pix/notifications.html', context)

def privacy(request):
    template = loader.get_template('pix/Privacy.html')
    context = {}
    rendered_template = template.render(context, request)
    return HttpResponse(rendered_template)

def Terms(request):
    template = loader.get_template('pix/Terms.html')
    context = {}
    rendered_template = template.render(context, request)
    return HttpResponse(rendered_template)

# def settings_view(request):
#     profile = get_object_or_404(Profile, user=request.user)

pix/templates/pix/collection_purchase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'pix/style.css' %}">
    <!--TITLE-->
    <title>Pixel Vault</title>
  </head>
 
<body>
     
  <nav class="navbar">

    <div class="left">
        <a href="{% url 'pix:index' %}"> 
          <img class="logo-img" src="/static/pix/images/Pixelvault black background.jpg">
        </a>
    </div>
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>

    <div class="right">
      {% if user.is_authenticated %}
      <div class="user-icon">
        <a href="{% url 'pix:dashboard' %}" id="user-icon" style="display: flex; justify-content: center; align-items: center; width: 40px; height: 40px; border-radius: 50%; background: white;
        ;  transform: translate(-50%, -50%);">
          {% if user.profile.profile_picture %}
          <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" style="width: 98%; height: 98%; border-radius: 100%;">
          {% else %}
          <img src="/static/pix/images/iconmonstr-user-circle-thin-240.png" alt="Default Picture" style="max-width: 50%; max-height: 50%;">
          {% endif %}
        </a>
      </div>
                
<div class="dropdown-container" id="dropdown-container" style="position: relative; z-index: 3;">
<button onclick="toggleDropdown()" class="dropdown-button" style="background: none; border: none; cursor: pointer;">
<img src="/static/pix/images/dropdown menu icon.png" alt="Dropdown Icon" style="width: 30px; height: 30px; background: white; margin-bottom: auto; border-radius: 2px; margin-top: .25rem;" >
</button>
<div id="dropdownContent" class="dropdown-content" style="display: none; position: absolute; top: 100%; right: 0;border: 1px solid #ddd; border-radius: 3px; padding: 10px; transition: right 0.5s;
background: linear-gradient(to bottom right, blue, red, purple);
background: white; color: black;">
<a class="sub-text" href="{% url 'pix:notifications' %}" class="dropdown-item" style="display: block; color: #333; text-decoration: none; padding: 8px 0; border-bottom: 1px solid black; color: black;">Notifications</a>
<a class="sub-text" href="{% url 'pix:collections' %}" class="dropdown-item" style="display: block; color: #333; text-decoration: none; padding: 8px 0; border-bottom: 1px solid black; color: black;">Collections</a>
<a class="sub-text" href="{% url 'pix:create' %}" class="dropdown-item" style="display: block; color: #333; text-decoration: none; padding: 8px 0; border-bottom: 1px solid black; color: black;">Create</a>
<a class="sub-text" href="{% url 'pix:settings' %}" class="dropdown-item" style="display: block; color: #333; text-decoration: none; padding: 8px 0; border-bottom: 1px solid black; color: black;">Profile</a>
<a class="sub-text" href="{% url 'pix:explore' %}" class="dropdown-item" style="display: block; color: #333; text-decoration: none; padding: 8px 0; border-bottom: 1px solid black; color: black;">Explore</a>
<form method="POST" action="{% url 'pix:logout' %}" style="display:inline;">
  {% csrf_token %}
  <button class="sub-text" type="submit" style="background: none; border: none; cursor: pointer; padding: 8px 0; width: 100%; text-align: left; color: black;">Logout</button>
</form>
</div>

<script>
function toggleDropdown() {
var dropdownContent = document.getElementById("dropdownContent");
if (dropdownContent.style.display === "block") {
  dropdownContent.style.display = "none";
} else {
  dropdownContent.style.display = "block";
}
}
</script>
</div>

      {% else %}
      <div class="login-register-links" style="z-index: 100; display: flex; flex: row; gap: .5rem;" >
        <a href="{% url 'pix:login' %}" style="color: beige; text-decoration: underline; margin-right: 10px; background: green; padding: .3rem .6rem; border: none; border-radius: 23px; text-decoration: none;
          font-size: .7rem;
          letter-spacing: 2px;
          font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
          font-weight: bold; background: transparent; padding: .6rem 1rem; border: none; border-radius: 23px; text-decoration: none; color: white;
         z-index: 102; border: 1px white solid;
         z-index: 101;" class="login-btn">LOGIN</a>
        <a href="{% url 'pix:register' %}" style="color: white; text-decoration: underline;
          font-size: .7rem;
          letter-spacing: 2px;
          font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
          font-weight: bold; background: white; padding: .6rem 1rem; border: none; border-radius: 23px; text-decoration: none; color: black;
         z-index: 102;  border: 1px white solid; " class="register-btn">REGISTER</a>
      </div>  
      {% endif %}
    </div>
  </nav>


    <div class="notified" style="color: white; font-family: Arial, Helvetica, sans-serifj; font-weight: bold;">The owner of the collection has been notifed, Please wait for them for them to approve the purchase </div>



    <!-- Display user's images -->
    <div class="image-gallery">
      {% for image in user_images %}
          <div class="image-card">
              <img src="{{ image.image.url }}" alt="{{ image.name }}">
              <p>{{ image.name }}</p>
              <p>Category: {{ image.category }}</p>
              <p>Price: {{ image.price }}</p>
          </div>
      {% endfor %}
  </div>
    
    <canvas id="c" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: -1;"></canvas>
    <script src="/static/pix/js/script.js"></script> 
    

  <!-- new footer start  -->

  <footer class="site-footer">
    <hr>
    <div class="footer-content">
        <!-- <div class="footer-section">
            <p class="footer-header">SERVICES</p>
            <div class="links">
                <a href="{% url 'pix:explore' %}">Explore</a>
                <a href="{% url 'pix:create' %}">Create</a>
                <a href="{% url 'pix:explore' %}">Trade</a>
            </div>
        </div> -->

        <div class="footer-section">
            <!-- <p class="footer-header">CONTACT</p> -->
            <div class="links">
              <a href="https://t.me/pixelvault_live">USER SUPPORT</a>
            </div>
        </div>
        
        <div class="footer-section">
            <!-- <p class="footer-header">CONTACT</p> -->
            <div class="links">
              <a href="{% url 'pix:Terms' %}">TERMS OF USE</a>
            </div>
        </div>

        <div class="footer-section">
            <!-- <p class="footer-header">LEGAL</p> -->
            <div class="links">
                <!-- <a href="{% url 'pix:Terms' %}">Terms of Use</a> -->
                <a href="{% url 'pix:Privacy' %}">PRIVACY POLICY</a>
            </div>
        </div>
    </div>
</footer>


  <!-- new footer end -->
  

    <!-- js for scroll pop up effect start  -->
    <script>
      // script.js
document.addEventListener('DOMContentLoaded', function() {
    const elements = document.querySelectorAll('.fade-in-element');

    const handleScroll = () => {
        const windowHeight = window.innerHeight;
        elements.forEach(element => {
            const elementTop = element.getBoundingClientRect().top;
            if (elementTop < windowHeight - 50) {
                element.classList.add('visible');
            } else {
                element.classList.remove('visible');
            }
        });
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll(); // Run on initial load
});

    </script>
    <!-- js for scroll pop up effect end -->
    
    <style>


.fade-in-element {
    opacity: 0;
    transform: translateY(20px);
    transition: opacity 0.6s ease-out, transform 0.6s ease-out;
    margin-top: 20px ;
}

.fade-in-element.visible {
    opacity: 1;
    transform: translateY(0);
}

    </style>


  </body>




    <style>
      .navbar{
        padding: 3px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        /* border: 1px solid #ccc; */
        height: 8vh;
      }
      
      .logo-img{
        height: 38px;
        width: 38px;
      }

      .right{
        z-index: 3;
        display: flex;
        flex-direction: row;
      }

      .user-icon{
        position: relative;
        top: 19px;
      }

      /* .body-container{
        border: solid 1px white ;
      } */

      .welcome-txt{
        padding-left: 1rem;
        transition: all ease-in 1s;
      }
      .intro-text{    
        color: beige; 
        top: 10%; 
        font-size: 2rem;
        font-family: Arial, Helvetica, sans-serif;
      }

      .orange-text{
        /* color: orangered; */
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        font-size: 3rem;
        font-weight: bolder;
        font-style: italic;
        background: linear-gradient(to right, purple, red);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
      }
      
      .sub-text{
        color: beige;
        font-size: 1rem;
        letter-spacing: 2px;
        width: 70%;
        font-family: monospace;
      }

      .nft-slider-wrapper, .nft-slider{
        padding: 1rem;
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        align-items: center;
      }

      .nft-slider-img{
        width: 50%;
        border-radius: 10px;
        padding: 1rem;
      }

      .homepage-tran{
        padding: 1rem;
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        align-items: center;
      }

      
      /* SLIDER CODE */


/* CSS styles */
.container {
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: center;
  padding: 2rem;
}

.slider {
  display: flex;
  transition: transform 0.5s ease;
  justify-content: space-around;
  align-items: center;
  background: linear-gradient(to bottom right, purple, red);
  transition:all  ease-out 1s;
  border-radius: 15px;
  padding-bottom: 2rem;
}

.slider-image{
  max-width: 350px;
  min-width: 300px;
  max-height: 350px;
  min-height: 300px;
  border-radius: 20px;
  scale: 90%;
}

.button {
  position: absolute;
  top: 50%;
  /* transform: translateY(-50%); */
  cursor: pointer;
  background-color: beige;
  border-radius: 100%;
  padding: 10px;

}

.slider-metadata{
  font-weight: bold;
  font-size: medium;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  margin-top: 10px;
  padding-left: 1rem;
}

.owner, .price{
  font-weight: 400;
  font-size: small;
}

.prev {
  left: 0;
}

.next {
  right: 0;
}

.slider-price{
  font-weight: bold;
  font-size: medium;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;

}
  
.Explore-btn{
  background-color: blue;
  border-radius: 20px;
  justify-content: space-around;
  width: fit-content;
  padding: 9px 9px;
  cursor: pointer;
  font-weight: bold;
  font-size: medium;
  border: none;
  margin-top: 1rem;
}

.Explore-btn:hover{
  transition: 0.5s;
  scale: 1.03;
  background-color: rgba(0, 0, 255, 0.644);
  box-sizing: 2px 2px 3px black;
}

.metadata-title{
  font-size: small;
  font-weight: 400;
}

.homepage-tran{
  display: flex;
  width: 70%;
  justify-content: center;
  margin: auto;
}

.transaction{
  width: 31%;
  height: 190px;
  border: solid none;
  background: linear-gradient(to bottom right, blue, red, purple);
  margin: auto;
  border-radius: 6px;
}
.transaction .img-container{
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 1rem;
}

.transaction .t-img{
  padding: 1rem;
  height: 1rem;
  width: 1rem;
}

.transaction .txt-container{
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 0 1rem;  
  align-items: center;
  margin: auto;
}

.transaction .intro-text{
  font-size: .7rem;
  font-weight: bold;
}

.transaction .sub-text{
  font-size: .5rem;
  margin-top: 1rem;
  padding: auto;
}

.login-btn:hover, .register-btn:hover{
        scale: 1.07;
        opacity: .9;
        transition: all ease-in .5s;
      }



/* new footer styling start  */


.site-footer {
    background: transparent;
    color: white; /* Light text color */
    /* padding: 40px 0; */
    margin-top: 20px;
}

.footer-content {
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    justify-content: space-around;
    flex-wrap: wrap;
}

.footer-section {
    flex: 1 1 300px; /* Flexbox properties for responsive layout */
    margin-bottom: 20px;
    text-align: center;
}

.footer-header {
    font-size: 1.2rem;
    font-weight: bold;
    margin-bottom: 10px;
}

.links a {
    display: block;
    color: white;
    text-decoration: none;
    margin-bottom: 8px;
    transition: color 0.3s;
}

.links a:hover {
    color: #007bff; /* Primary color or a color of your choice */
}


.footer-section{
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-around;
}

.footer-section .links{
  display: flex;
  flex-direction: row;
  gap: 1rem;
  color: white;
  padding-top: 1rem;
  font-weight: bold;
  font-family: Arial, Helvetica, sans-serif;
}

/* new footer styling end */
      


</style>


<body>

</html>